spring.application.name=socialbotlabs-bot

server.servlet.context-path=/authorization-server
server.address=0.0.0.0
server.port=8088

social.botty.default.role=${DEFAULT_ROLE}
social.botty.default.login.page = ${LOGIN_PAGE_FORM}
social.botty.default.logout.page = ${LOGOUT_PAGE_FORM}

#DataSource Configuration
#MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/botty
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.open-in-view=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create

#Datos Iniciales

# Activar la ejecución de scripts SQL al inicio de la aplicación
spring.datasource.initialize=true

# Definir el archivo SQL a ejecutar al iniciar la aplicación
spring.datasource.schema=classpath:import.sql

# (Opcional) Si quieres ejecutar scripts de inicialización solo una vez, por ejemplo, al crear la base de datos:
spring.datasource.data=classpath:import.sql

# Asegurarse de que se ejecuta el script después de que la base de datos esté configurada
spring.sql.init.mode=always


# Pool connections configuration (HikariCP)
spring.datasource.hikari.maximum-pool-size=150
spring.datasource.hikari.minimum-idle=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.leakDetectionThreshold=15000
# Otras configuraciones adicionales (opcional)
spring.datasource.hikari.pool-name=BottyConnectionPool


spring.security.oauth2.client.registration.google-idp.provider=google
spring.security.oauth2.client.registration.google-idp.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google-idp.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google-idp.scope=openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
spring.security.oauth2.client.registration.google-idp.client-name=cliente-angular
spring.security.oauth2.client.provider.google.user-name-attribute=email


spring.security.oauth2.client.registration.github-idp.provider=github
spring.security.oauth2.client.registration.github-idp.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github-idp.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github-idp.scope= user:email, read:user
spring.security.oauth2.client.registration.github-idp.client-name=Sign in with GitHub
spring.security.oauth2.client.provider.github.user-name-attribute=login

#logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.security.oauth2=TRACE
