spring.application.name=socialbotlabs-bot

server.servlet.context-path=/authorization-server
server.address=0.0.0.0
server.port=8088

social.botty.default.role=${DEFAULT_ROLE}

#DataSource Configuration
#MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/botty
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.open-in-view=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Pool connections configuration (HikariCP)
spring.datasource.hikari.maximum-pool-size=150
spring.datasource.hikari.minimum-idle=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.leakDetectionThreshold=15000
# Otras configuraciones adicionales (opcional)
spring.datasource.hikari.pool-name=BottyConnectionPool